### ISSUE TITLE
依赖失败

### ISSUE THREAD

**Issue by Jooyer** [NanoMichael/AndroidLaTeXMath#1]
大佬,依赖库一直失败,能否使用 jitpack 发布一次呢?

**Comment by NanoMichael** [comment]
github 咋没给我发邮件啊，一直没看到你的消息，我晚上看一下重新发布一下试试。你也可以直接 clone 下来按照文档编译一下，很简单的。你有没有在 root project 的 build.gradle 下添加 jcenter：

```groovy
allprojects {
   repositories {
       jcenter()
      // ...
   }
}
```

**Comment by Jooyer** [comment]
大佬,能直接把你编译好的 so 库提交分享下么,  我这边还是依赖失败:
ERROR: Failed to resolve: io.nano:android-tex:1.0.0
Show in Project Structure dialog
,必要的 jcenter() 配置,都是正常配置的!

**Comment by NanoMichael** [comment]
很抱歉，我之前只是把库上传到了 bintray 上了，而没有发布到 jcenter。现在在 `build.gradle` 添加：

```groovy
implementation 'io.nano:android-tex:1.0.0'
```

应该可以正常使用了。有任何问题可以再反馈给我。:smile:

**Comment by Jooyer** [comment]
大佬,可以了! 
![image](https://user-images.githubusercontent.com/22199100/66741079-440a8500-eea7-11e9-9ae2-db6d87f3264c.png)

**Comment by NanoMichael** [comment]
👏
