### ISSUE TITLE
本库兼容LaTex原生语法问题

### ISSUE THREAD

**Issue by Jooyer** [NanoMichael/AndroidLaTeXMath#3]
大佬:
       早上好!
我拷贝一段LaTex原生语法如下:
\documentclass{article}
\usepackage{ctex}
\begin{document}
你好，LaTeX
\end{document}

,然后利用本demo中的TexView的setLaTeX(),发现无法正常显示,大佬方便留个微信号/QQ号,我向大佬请教下,我的 微信/QQ 均是  712952521 .

**Comment by NanoMichael** [comment]
本库不支持（也不打算支持）所有的 LaTeX 命令，本项目的目标是实现实时的/方便嵌入到应用的/跨平台的`数学公式`（目前正打算支持 `def` 命令，用以支持自定义宏）编译和渲染的库，小巧和跨平台是主要目标，用以配合所在平台的文本渲染来展示 LaTeX 片段，因此有关文档的操作命令都不会支持。

你提到的 LaTeX 代码中，`\begin{document}` 开始一个文档，`\end{document}` 结束本文档，因为不支持文档，可以这么来写:

```java
final String ltx = "\\text{你好，\\LaTeX}";
final TeXView v = findViewById(...);
v.setLaTeX(ltx);
```

任何问题都提到 Github 的 issue 上吧，以后好追踪。另外如果要学习 TeX 语法，推荐阅读一下 [The TeXBook](http://www.ctex.org/documents/shredder/src/texbook.pdf)。

**Comment by Jooyer** [comment]
好的,多谢大佬!
