### ISSUE TITLE
demo运行异常

### ISSUE THREAD

**Issue by Jooyer** [NanoMichael/AndroidLaTeXMath#4]
大佬:
   你好,我打算运行你的demo看看,发现clone下来,运行不起! 麻烦看哈代码提交是否完整!

**Comment by NanoMichael** [comment]
这个工程因为没有上传编译好的 so 文件，所以直接运行是不行的。你需要先编译 c++ 库，按照如下步骤：

- 确保 NDK 已经安装，版本 `>= 4.9`
- 在 `local.properties` 文件中加入以下配置：
```
ndk.dir=/your/NDK/dir
```
- 更新 submodule
```
git submodule update --remote
```
最后直接编译运行即可

**Comment by Jooyer** [comment]
好的，大佬，我试试！多谢大佬------------------ 原始邮件 ------------------
发件人: "Nano"<notifications@github.com>
发送时间: 2020年3月16日(星期一) 晚上8:44
收件人: "NanoMichael/AndroidLaTeXMath"<AndroidLaTeXMath@noreply.github.com>;
抄送: "Jooyer"<712952521@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NanoMichael/AndroidLaTeXMath] demo运行异常 (#4)




 
这个工程因为没有上传编译好的 so 文&#x4EF6;，所以直接运行是不行的。你需要先编译 c++ 库，按照如下步骤：
  
确保 NDK 已经安装，版本 >= 4.9
 
在 local.properties 文&#x4EF6;中加入一下配置：
  ndk.dir=/your/NDK/dir   
更新 submodule
  git submodule update --remote  
最后直接编译运行即可
 
&mdash;
