### ISSUE TITLE
设置字体后,文本宽度超过屏幕宽度,没有换行!

### ISSUE THREAD

**Issue by Jooyer** [NanoMichael/AndroidLaTeXMath#5]
大佬:
   我虽然clone了项目,可惜不会C++,还是没能解决如下bug:
  魅族16S,  1080*1920.
  1. 设置文本
     tv_latex.setLaTeX("sqrt[3]{(x-y)^3}=x^2-3*xy+y^2  \\overline{a+b}")
  2. 修改显示宽度 , textSize = 40
       public void setLaTeX(String ltx) {
        int w = getWidth();
        if (w == 0) w = 1080;  // 这里设置屏幕宽度
        render = LaTeX.instance().parse(ltx, w, textSize, 10, Color.parseColor("#6200EE"));
        requestLayout();
    }
 3. 调用设置文字大小方法
          tv_latex.setTextSize(80) // 最开始文本大小设置的是40, 现在修改为80

屏幕显示不完整,即没有换行显示! 希望大佬修改下这bug!

**Comment by NanoMichael** [comment]
能贴张图吗？

**Comment by Jooyer** [comment]
大佬:
     今儿早上测试正常换行了,就是会提前换行(没到末尾)!麻烦看哈换行问题!
![1](https://user-images.githubusercontent.com/22199100/77376523-7ea81000-6dab-11ea-8925-587663dc6aef.png)
![2](https://user-images.githubusercontent.com/22199100/77376525-7fd93d00-6dab-11ea-80dc-47de9c57aba6.png)
![3](https://user-images.githubusercontent.com/22199100/77376528-8071d380-6dab-11ea-9c3c-3ec656b731e8.png)

**Comment by NanoMichael** [comment]
这是正常的。看起来你对 LaTeX 语法不是很熟悉，推荐简单看下[这个](https://www.overleaf.com/learn/latex/Mathematical_expressions)。这个库目前支持 LaTeX 的一部分语法，对于 TeX 原语（`\def` 等命令）还不支持。

对于数学公式来说，不换行才是正确的处理。尽管如此本库依然处理了换行的情况，会选择在`最合适`的地方换行（可参考 [ICU 换行算法](http://userguide.icu-project.org/boundaryanalysis)）。如果你需要在任何地方都能换行，可以在需要渲染的命令之前添加 `\breakEverywhere{true}` 命令开启，或者通过 `\breakEverywhere{false}` 关闭，⚠️这不是 TeX 标准命令。

关于更多的自定义命令，可参考[这里](https://github.com/NanoMichael/cLaTeXMath)。

**Comment by Jooyer** [comment]
多谢大佬,我再看看!
