### ISSUE TITLE
latex.h not found

### ISSUE THREAD

**Issue by mikeroneer** [NanoMichael/AndroidLaTeXMath#6]
When I try to run the demo application, I get the following error:
```
jni/port/jni_latex.cpp:4:10: fatal error: 'latex.h' file not found
```

**Comment by NanoMichael** [comment]
Have you run the following commands to fetch the C++ implementation?

```sh
git submodule init --recursive
git submodule update --remote
```

**Comment by mikeroneer** [comment]
Hi @NanoMichael,
thank you for the fast response. The crucial hint was to also initialize the submodule, I couldn't find this in the readme - thank you for updating the already!
Even though the installation now times out, this issue can be marked as resolved.
