### ISSUE TITLE
Reflection crash

### ISSUE THREAD

**Issue by YvesCheung** [NanoMichael/AndroidLaTeXMath#8]
Proguard rule
```
-keep class io.nano.tex.**
```
should be replaced with
```
-keep class io.nano.tex.** {*;}
```
Otherwise, crash happen: `java.lang.NoSuchFieldError: no "F" field "x" in class "Lio/nano/tex/Rect;" or its superclasses`

**Comment by NanoMichael** [comment]
this is indeed an issue that hasn't been tested. If you're interested, feel free to submit a pull request. And if you're interested, you can take a look at [this project](https://github.com/NanoMichael/MicroTeX/tree/openmath).

**Comment by YvesCheung** [comment]
It's an excellent library 👍

**Comment by YvesCheung** [comment]
#9 Pack the proguard rules into aar, so users don't need additional configuration:

<img width="471" alt="image" src="https://github.com/NanoMichael/AndroidLaTeXMath/assets/18024705/e34edc45-1e8f-415d-b3cd-970da471680d">

**Comment by NanoMichael** [comment]
This issue can be closed now.
